### ISSUE TITLE
Missing dependency: docopt

### ISSUE THREAD

**Issue by RonaldPK** [isbg/isbg#23]
When I run a command like 
``python isbg.py --imapuser me --savepw --spaminbox Junk``
I get the error "Missing dependency: docopt" and "Option processing failed - name 'docopt' is not defined"

I suppose that is because my new and shining Debian server does not have python-docopt installed. Unfortunately, there is no such package yet for Debian stable. Does that mean I'll have to stick to isbg 0.99?

**Comment by baldurmen** [comment]
Sadly, as you pointed out, python-docopt is pretty recent and thus has not reached stable yet. I see 3 options for you:

**1 - Install python-docopt from jessie:**
* update your `/etc/apt/sources.list` to include `jessie`
* `aptitude install -t jessie python-docopt`

I cannot recommend this, since it may (or may not) cause you some dependencies trouble. We all know what a pain is maintaining a Debian server with some `sid` components.

**2 - Install docopt from pip:**
* `aptitude install pip`
* `pip install docopt`

I'm not fond of pip. I think uninstalling things is pretty useful, and pip can't do this.

**3 - Download docopt from https://pypi.python.org/pypi/docopt/ and copy docopt.py in your isbg directory.**

Docopt is self-contained (yay!).
I have not tested this, but I think you might even not have to tweak isbg.py. The way python parses classes, it should be fine.

To me, this seems by far to be the best solution.

**Comment by RonaldPK** [comment]
Thank you baldurmen, the third option works excellent.

**Comment by jcharaoui** [comment]
4- Create a backport package : https://wiki.debian.org/SimpleBackportCreation

**Comment by bjd-pfq** [comment]
$ isbg.py  --imaphost  myserver.com  --savepw
IMAP password for @myserver.com
^C

What?! where is the Username preceding  @myserver.com?
 
$ isbg.py --imaphost foo@myserver.com  --savepw
IMAP password for @foo@myserver.com:

What?!  An AT-sign in a Usrename?!

FAIL

**Comment by baldurmen** [comment]
Hmmm, this issue is closed and I can't see the link between the problem you seem to have and this (closed) issue.

Then again, I'm not sure I understand what your issue exactly is. Could you be more specific?
