### ISSUE TITLE
modify the script to learn from forwarded mails

### ISSUE THREAD

**Issue by cmichallek** [isbg/isbg#42]
Hi,

i've created a spam inbox where everybody can forward their spams to. so some people send an email with multiple attachments there. the real spam is inside the attachments.
currently im using some awkward combination of fetchmail and some homebrew shell scripts with mu, to extract the attachments and then learn them.

could that be integrated with isbg? would be really cool.

**Comment by baldurmen** [comment]
I'm not sure I understand what you are asking. You created a spam inbox for everyone (me, your uncle, my friendly neighborhood tech club) to send spams to so you can learn from them?

If that is the case, you should know bayesian filters don't take a lot of emails to train. From SA's doc:
> The bayesian classifier can only score new messages if it already has 200 known spams and 200 known hams.

Using other people's emails to train your filter could actually poison them, so it's normally not recommended.

Please clarify you thoughts if I did not get it right.

**Comment by cmichallek** [comment]
its for a central amavis spamfilter.
when spam gets regularly past the filter, we collect these in a central mailbox and i feed them to sa-learn now  and then.

**Comment by baldurmen** [comment]
Ok, now I get it, the attachment thing is pretty clever since you don't want to mess the headers.

Still, why don't you just run  --learnspambox on all the accounts with cron?

To answer your original question, no, I have no plan to support reading "spam attachments". There is a lot a of work to do on isbg to clean out the code and this is my priority. And since I don't have a great deal of time and it seams I'm the only one willing to do work for now, it might take while...

Still, python is pretty simple and ISBG is only a few hundred lines of code. If you submit a nice PR I certainly won't refuse it!

**Comment by cmichallek** [comment]
thanks for the reply!

my mail backend behind the mailgateway is an exchange :/ thats why im using this convoluted solution :)

I got pretty rusty when it comes to coding, but ill take a look when got some time.
good luck with the code cleanup :)
