### ISSUE TITLE
Daemon mode

### ISSUE THREAD

**Issue by vinzent** [isbg/isbg#59]
right now I run isbg as cronjob. Everytime it logs in and scans the INBOX for new mails.

It would be nice if isbg would provide a daemon mode where it only connects once to the IMAP server and then waits for new incoming mails to be scanned. 

https://en.wikipedia.org/wiki/IMAP_IDLE

**Comment by baldurmen** [comment]
If this is ever implemented, it'll be after version 2.0.

This seems neat, but I think the cronjob does the work for now.

**Comment by baldurmen** [comment]
The way to go forward with this is with systemd unit files. It's going to make manual install a little more complex, but once properly packaged it won't be a problem.

**Comment by baldurmen** [comment]
Reading up a bit more on this, `imaplib` (the python3 standard library we are using) doesn't really support IDLE. You can make it do it, but it's an ugly hack and I'd prefer not to do that. Chances are it would be buggy and not very stable.

One solution could be to use `imaplib2`. It supports IDLE (and a bunch of other nice things), but it seems it hasn't really been maintained since Piers Lauder left (https://github.com/imaplib2/imaplib2/issues/7). I have no desire to switch to a library that's not in the standards and is unmaintained :)

So I'll mark this as "won't fix". [If magically imaplib is replaced by a maintained version of imaplib2](https://bugs.python.org/issue11245), I'd be happy to reconsider.
